version: 0.0
os: linux
files:
    - source: /
      destination: /var/www/html/test-cicd
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: deploy-scripts/before_install.sh
      runas: ubuntu
  #AfterInstall:
  #  - location: deploy-scripts/setup_env.sh
  #    timeout: 300
  #    runas: ubuntu
  #  - location: deploy-scripts/set_file_permission.sh
  #    timeout: 300
  #    runas: ubuntu
  # ApplicationStart:
  #   - location: script/start_server.sh
  #     timeout: 300
  #     runas: ubuntu
  # ApplicationStop:
  #   - location: script/stop_server.sh
  #     timeout: 300
  #     runas: ubuntu
